### ISSUE TITLE
Missing translation in notification widget

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#103]
Is it possible to translate also the time description in the widget? Currently it shows only english messages.
![Bildschirmfoto 2022-02-04 um 09 10 37](https://user-images.githubusercontent.com/10132368/152750027-4a271605-290d-4ad6-a206-e6995653709e.png)

**Comment by SebastianStehle** [comment]
The widget is available in German and English: https://github.com/notifo-io/notifo/blob/main/frontend/src/sdk/shared/config.ts#L11

Seems that the locale is not set when adding the widget to the website.
