### ISSUE TITLE
SMTP authentication is required

### ISSUE THREAD

**Issue by lukasmatt** [notifo-io/notifo#108]
Hey,

I just tried testing Notifo with mailcatcher. This doesn't work since you cannot configure a SMTP Server without authentication.
A minor thing, still worth considering, since people may use open relays to communicate.

// Lukas

**Comment by SebastianStehle** [comment]
How do you mean that? I think no SMTP server works without authentication. Therefore you can enter username and password.

**Comment by lukasmatt** [comment]
At least not a public one. But I can imagine several scenarios in which an OpenRelay makes sense.

**Comment by SebastianStehle** [comment]
I am still confused. The SMTP integration requires username and password:

![image](https://user-images.githubusercontent.com/1236435/160380907-8881e21b-e339-4255-8ae0-83b308049982.png)

Is this another authentication method you are talking about?

**Comment by lukasmatt** [comment]
> The SMTP integration requires username and password

exactly :) I have a setup where the SMTP server has no authentication configured ([Open relay](https://en.wikipedia.org/wiki/Open_mail_relay)).

**Comment by SebastianStehle** [comment]
Now I get. I have not read your initial post carefully enough  .... sorry. You want SMTP WITHOUT authentication.

**Comment by lukasmatt** [comment]
> Now I get. I have not read your initial post carefully enough .... sorry. You want SMTP WITHOUT authentication.

yes, the title was probably misleading / too generic .. sorry about that

**Comment by SebastianStehle** [comment]
There is a PR for that.

**Comment by lukasmatt** [comment]
That was quick ;) Thanks
