### ISSUE TITLE
iOS 15.4 will support WebPush

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#121]
In the recent iOS and IPadOS Versions there will be support for WebPush.
Currently there seems to be some bugs in the beta but we should follow this.
Would be a great extension if we could use web push also on apple devices.
[https://firt.dev/ios-15.4b](https://firt.dev/ios-15.4b)

**Comment by SebastianStehle** [comment]
But the link says it does not work yet.

**Comment by CR4567** [comment]
yes this was just meant as a reminder.
It seems it's still work in progress but could be finished in one of the next releases.

**Comment by CR4567** [comment]
https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_safari_and_other_browsers
should now work also with ios. I will check this out as soon as possible

**Comment by CR4567** [comment]
good news for all who wants use that functionality, it seems to work out of the box :-)
It's only important to install the pwa on the mobile phone and accept push.
