### ISSUE TITLE
Create Admin User Failure

### ISSUE THREAD

**Issue by MuhmdHsn313** [notifo-io/notifo#130]
Hello
I tried to create a new admin user by Installation page `http://localhost/account/setup`  but account doesn't created, and l can login to dashboard.
I use docker compose [docker-compose-noproxy.yml](https://github.com/notifo-io/notifo/blob/main/deployment/docker-compose/docker-compose-noproxy.yml), Version: 1.2.1

Thanks...

**Comment by SebastianStehle** [comment]
Thanks. I tested it. THe password requirements are not met and it is not shown properly. I will fix that. Use a special character and uppercase character.

**Comment by SebastianStehle** [comment]
![image](https://user-images.githubusercontent.com/1236435/185350182-46faf8ee-ec55-485e-9094-587b30a812d9.png)
