### ISSUE TITLE
Notification Success Status in Overview

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#131]
Would it be possible to add the success status in the notifications overview?
Success is maybe hard to measure but for me it would mean at least one channel received the message and maybe also opened it?
![Bildschirmfoto 2022-09-02 um 12 33 51](https://user-images.githubusercontent.com/10132368/188121416-12aac925-3e15-4eee-896b-f983e55efd7f.png)

Maybe two Icons symbolising the two states would be good.

This would help a lot in finding issues in the notifications.

**Comment by SebastianStehle** [comment]
I would prefer something that is not tailored to your needs. a percentage or something like this.

**Comment by CR4567** [comment]
I don't think that this is a tailored need. Should be a relevant information for everyone if a notification was successfully sent and received.
The way how it's presented is less important, if the information is transported in some way.

**Comment by SebastianStehle** [comment]
I mean the definition of success is very specific, but we can give it another name.

**Comment by SebastianStehle** [comment]
![Untitled](https://user-images.githubusercontent.com/1236435/188487355-9e2de735-d68c-4f6d-8a47-ddb0a716c046.png)
