### ISSUE TITLE
SMS Sender Name

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#152]
Would be nice if we could set the sender name for sms.
In some cases it's not necessary or not wished to give people the sender phone number and shows instead a nice marketing name

**Comment by SebastianStehle** [comment]
I am not aware that this is possible. I have never seen it in an SMS API.

**Comment by CR4567** [comment]
![Bildschirmfoto 2022-11-22 um 09 21 48](https://user-images.githubusercontent.com/10132368/203262314-df4b48d1-a4d7-446f-818a-7611a774b2db.png)
This is from the messagebird api doc. Originator can be set to phone number or an alphanumeric value
