### ISSUE TITLE
Variables in email subject

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#153]
Is there a reason why we shouldn't use variables in the email subject?
It's often helpful to include specific notification params into the subject. In these cases the user doesn't even have to open the mail.
eg. Event 'xyz' occured

**Comment by SebastianStehle** [comment]
It is possible, but the syntax is different. In Liquid you have to do `notifications[0].properties.property` I think.

**Comment by CR4567** [comment]
Ah you're right. 
This was not working:
`notifications[0].properties.property`
But this
`{{ notifications[0].subject }}`

Thanks a lot for the hint ;-)

**Comment by SebastianStehle** [comment]
Depends what you use as property ;)
