### ISSUE TITLE
Track mobile token usage

### ISSUE THREAD

**Issue by SebastianStehle** [notifo-io/notifo#157]
If you expect the user to get a mobile push message it is sometimes hard to track why nothing has not been sent. Usually the root cause is that there was no mobile push token at the time.

So the user request was to store the timestamp for each mobile push token, but this would not help, because you need full history to determinate whether there was a mobile push token. 

So the idea is:

1. Implement a simple history for user and app settings.
2. Introduce a flag `ExpectSent` to the channel settings, e.g. you can say that you expect that the mobile push message will be sent. If this flag is true and and there is no configuration (aka Mobile Push Token), we will log that to the output and write it to the history.

**Comment by xamplum** [comment]
Great suggestion!

A token history would nevertheless be useful to support the trouble shooting process. In Addition to your suggestion i propose:
- Do not delete invalidated Token. **Mark them as invalidated** instead.
- Show token history (at least for a few weeks) alongside with `created_at `and `invalidated_at `timings.

**Comment by SebastianStehle** [comment]
What would be the benefit over my suggestions? In particular the history. I don't see that.

**Comment by xamplum** [comment]
We have customers who very rarely receive notifications. Your suggestion allows me to recognise when a message that was supposed to be delivered could not be delivered.

Additional information could be helpful in determining the cause.
What information do you intend to provide as part of the "simple user and app settings history"?

**Comment by SebastianStehle** [comment]
Every user and the app would have its own history. With something like 

```
* [DATE]: Token **TOKEN123** has been removed, because it is expired.
```

**Comment by SebastianStehle** [comment]
It has been implemented.

**Comment by CR4567** [comment]
I already deployed and tested it. Looks really good to me and I'm looking forward to the first debug sessions :-)
Just maybe one small improvement 
![Bildschirmfoto 2022-12-09 um 11 54 01](https://user-images.githubusercontent.com/10132368/206686749-05a1aa02-d3a6-491f-b68e-a321e32e6d05.png)
The mobile tokens are very long so you don't see the full message and only the code makes it hard to know whats going on.
Maybe we could show the full message in a mouseover or use bigger / collapsable rows?

**Comment by SebastianStehle** [comment]
I just removed the truncate thing:

![image](https://user-images.githubusercontent.com/1236435/206693047-e8384aff-40fd-4e6a-8461-69d4db8246c3.png)

**Comment by CR4567** [comment]
perfect 👍

**Comment by SebastianStehle** [comment]
Btw: I have decided to reuse the logging system, which aggregates the messages by text, code and system. But because we keep the token inside the message, it is very unlikely that it will be aggregated at all.

I have also introduced event codes, so you can query logs, for example in tests.
