### ISSUE TITLE
Unexpected Response Code 406 for WebPush

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#158]
I get lots of log entries about expected response code 406 when sending web push notifications.
Unfortunately I'm not able to see the correlation to an event or user. 

What's the exact meaning of this 406? Is it an issue or an expectable behaviour?
![Bildschirmfoto 2022-12-05 um 13 22 56](https://user-images.githubusercontent.com/10132368/205637936-e35d2ff2-94b1-462a-bcaa-0b408e237851.png)

**Comment by SebastianStehle** [comment]
I have no idea. For Edge it seems to be some kind of throttling: 

https://learn.microsoft.com/en-us/answers/questions/940324/406-not-acceptable-may-be-returned-when-sending-a.html

**Comment by SebastianStehle** [comment]
Do you know what kind of endpoints are related to this?

**Comment by CR4567** [comment]
hm you could be right. As mentioned I'm not absolutely sure which message/user is responsible for the error. But around these issues I have users with the wns tokens (https://wns2-par02p.notify.windows.com/w)
