### ISSUE TITLE
Additional information user history

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#165]
Would it be possible to extent the user history entries with additional information?
It already helps a lot but is still missing a lot of context information.
In the example of deleting a mobile push token, I'm missing informations like:
-  when was the token created initially
- for which device type (ios / android)
- for which device (device ID)

What do you think?

**Comment by SebastianStehle** [comment]
> * when was the token created initially

This is basically the timestamp (FirstSeen).

> * for which device type (ios / android)
> * for which device (device ID)

Sure, you could just update the log message and provide a PR: https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo.Domain/Log/LogMessage.cs#L222

**Comment by SebastianStehle** [comment]
Are you going to submit a PR?

**Comment by CR4567** [comment]
yes I will look into it.

**Comment by xamplum** [comment]
It would be nice to have exact date+time values for each message. Currently there are relative ones displayed

**Comment by SebastianStehle** [comment]
PRs are welcome.

**Comment by SebastianStehle** [comment]
Can I close this?

**Comment by CR4567** [comment]
I already looked into this but it wasn't that simple because some of the information needed, were not available at the point of time when creating the entry. They were also lot's of changes in the last time, so I have to look how it's handled now. But it would be still very helpful for us, so I would keep it open as a reminder for me, if it's ok for you.

**Comment by SebastianStehle** [comment]
ofc
