### ISSUE TITLE
Dead Links in readme

### ISSUE THREAD

**Issue by cod3master** [notifo-io/notifo#169]
The following links in the readme are dead.

https://raw.githubusercontent.com/notifo-io/notifo/blob/main/media/notifo!.pdf

https://github.com/notifo-io/notifo/backend/src/notifo/appSettings.json

https://github.com/notifo-io/notifo/blob/main/deployment/docker-compose.yml

**Comment by SebastianStehle** [comment]
Thanks a lot.
