### ISSUE TITLE
how to Account/Login page in first time.

### ISSUE THREAD

**Issue by awtkeithlin** [notifo-io/notifo#17]
I run notifo localy. ![image](https://i.imgur.com/cJ4ZPWO.png) and stuck in  https://localhost:3002/.well-known/openid-configuration request.
But  https://app.notifo.io/ will go to https://app.notifo.io/Account/Login  (https://imgur.com/uRHixcR.png)
What is next to do?

**Comment by SebastianStehle** [comment]
Hi,

I know that docs are missing. You have to run the backend as well as the frontend. Then go to https://localhost:5002

**Comment by awtkeithlin** [comment]
There is an error.The SSL connection could not be established, see inner exception. 
https://imgur.com/a/MjF5Eco

**Comment by SebastianStehle** [comment]
Just install the cert.

**Comment by SebastianStehle** [comment]
Does this work for you?

**Comment by awtkeithlin** [comment]
Yew I go to  Account/Login page.But I don't know acc/password for it . And Mongodb schema.

**Comment by SebastianStehle** [comment]
You can configure the initial users here: https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo/appsettings.json#L239

Or you use Google ;)

**Comment by SebastianStehle** [comment]
THe mongo collections are created automatically.
