### ISSUE TITLE
🚀 Feature: Add Mautic Integrations

### ISSUE THREAD

**Issue by domaingood** [notifo-io/notifo#170]
### 🔖 Feature description

[Mautic](https://www.mautic.org/what-is-mautic) provides free and open source marketing automation software available to everyone. Free email marketing software, lead management Like sendgrid 

### 🎤 Why is this feature needed ?

Its more then Email marketing

### ✌️ How do you aim to achieve this?

I want marketing automation on it.

**Comment by SebastianStehle** [comment]
Would you provide a PR?

**Comment by SebastianStehle** [comment]
I don't see the value. Notifo uses its own email formatting, so we cannot really use mautic for that. Then we would send emails to mautic which are then forwarded to the email server. So we just have one server in the middle which does not add enough value.
