### ISSUE TITLE
Discussion iOS WakeUp Push

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#173]
We have issues with receiving push notifications if the user if offline for some time (> 1h)
I was trying to understand the WakeUp Push behavior but I'm not sure if I fully understand. Maybe you can correct me if I'm wrong at some point.

It seems that a wake up push is send in two cases
1. A notification is send via mobile Push channel
2. A notification is confirmed as seen

I think case 1. is the reason for our issue. If I understand the timers correct, the wakeup is delayed for 30 seconds. Means the wakeup push is always send after the real notification. Because iOS is only saving the last notification the real notification is never send directly only via our pull mechanism. But if the wakeup notification is also delayed by apple or just not send completely, you will get the notifications only by the next event notification. This happened for some of our users in our last tests. Our at least this would be my explanation why they didn't receive the notifications when they come online again but later (ca. 2h)  when an event notification was triggered.

Case 2 should not be necessary if we load all pending notifications when receiving the first notification after coming online. It could just be a safety line if there is something wrong with the inital pull. Not sure if this is really helpful or could be an issue.

What do you think about these assumptions?

**Comment by SebastianStehle** [comment]
About case 2: I think the main reason for that, was to offload the pulling from service. because of the time constraint. Therefore we send the wakeup again to force the app to become online

The reason for the delay of the wakeup is that we want to offload the notification so that it cannot affect our normal notification it to improve error reporting and I do not really see an option here. But I guess every normal notification could also be a wakeup notification, so perhaps this is not needed.

**Comment by CR4567** [comment]
I agree, case 2 is related to the timing constraint in the notification service extension. In older versions of the sdk we only pulled after receiving the wake up message. Here it was necessary absolutely necessary. 

I'm not sure what's exactly the meaning of "offload the notification" and "improve error reporting". I don't think that a normal notification wakes up the main app. That's exactly the reason of the background notificaitons and they are very limited and must have the content-available flag and are not allowed to include any other user specific input.

But I just figured out some issue with the wake up message body and created a pull request. Maybe this helps to fix it.

**Comment by SebastianStehle** [comment]
> I'm not sure what's exactly the meaning of "offload the notification" and "improve error reporting".

I mean to push it back to the internal queue in squidex backend to have all the benefits of retry and so on.

> That's exactly the reason of the background notificaitons and they are very limited and must have the content-available flag and are not allowed to include any other user specific input.

I just thought a normal notification could also be a background notification.
