### ISSUE TITLE
Incorrect query parameter IncludeUnseen

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#175]
There is a query parameter IncludeUnseen when querying the notifications. But wouldn't we need the opposite?
That's the current condition:
`if (status.Status == ProcessStatus.Handled && (query.IncludeUnseen || status.FirstSeen == null))`

So we're always filtering for the unseen notifications and we would need a parameter to include the already seen. Or did I miss the point?

**Comment by SebastianStehle** [comment]
It should be != null I think. We should write an api test for that

**Comment by CR4567** [comment]
? I think the == is correct.
Typically we want all notifications that are handled and not already seen. 
The query parameter would be an additional option for just querying all notifications that are handled. Don't know when this is really necessary.

**Comment by CR4567** [comment]
ok did just spend some more time on this...
I think the initial reason for this endpoint was. different. It was "return all seen notifications and decide with the UnSeen property whether the unseen notifcications should be also queried"
Then the "==" would be wrong and should be "!=".
In our usecase we would get a lot more notifications and would need to check on client side whether we already received them. But I guess this would be the correct way.

**Comment by CR4567** [comment]
Does it make sense to have a more flexible option? Maybe an enum?: UnSeen / Seen / Both

**Comment by SebastianStehle** [comment]
Sure, make sense.
