### ISSUE TITLE
Difference Delivery Status Handled / Sent

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#187]
In recent versions of notifo there seems to be an issue with displaying the correct delivery status in the history.
The first value is always "-", although the message was sent. In my case it's related to mobile push, not sure if it's the same for other channels.
![Bildschirm­foto 2023-03-31 um 11 54 15](https://user-images.githubusercontent.com/10132368/229088466-9557e100-591a-4f12-a8ef-2d4cd5129ba7.png)
In the message details, the status is "sent", so I was wondering what's the difference between sent and handled because this number only counts the "handled" messages.

**Comment by SebastianStehle** [comment]
Can you also verify it in the notifications itself? What kind of channel?

**Comment by SebastianStehle** [comment]
I think I have renamed the status and forgotten to update everything.

This is the status. They are ordered.
https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo.Domain.Integrations.Abstractions/DeliveryStatus.cs

**Comment by CR4567** [comment]
it's the same for webpush I think.
In earlier versions I think we used handled as status when push provider accetped the message. Now it's changed to sent.
Maybe because of other integrations. For example for messagebird there is a difference between handled and sent.

Nevertheless for https://github.com/notifo-io/notifo/blob/main/frontend/src/app/pages/user/NotificationRow.tsx#L32
we have to decide whether we need another column for sent and sum both states.
I think the latter is fine.

**Comment by SebastianStehle** [comment]
Can we just talk about that via phone? Either this weekend or on monday.

**Comment by CR4567** [comment]
Fixed in recent version
