### ISSUE TITLE
Errors in Templates prevent Notification dialog from opening

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#19]
If there is an error in one of the template fields, e.g. invalid URL Style (tried a relative URL path), the whole 
dialog can't be opened.
![Bildschirmfoto 2021-02-15 um 12 17 43](https://user-images.githubusercontent.com/10132368/107939970-cf0dfa80-6f87-11eb-95d5-d242b891e919.png)

**Comment by SebastianStehle** [comment]
Hi, what do you mean with template fields?

**Comment by SebastianStehle** [comment]
You mean a notification link?

**Comment by CR4567** [comment]
yes, you're right.
