### ISSUE TITLE
Silent Mobile Push Fail

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#190]
Silent Mobile Push result in a "failed" state with description "Field is required".
Confusing is that firstDelivered and firstSeen ist set, so maybe not a really an issue.

![Bildschirm­foto 2023-04-28 um 13 54 25](https://user-images.githubusercontent.com/10132368/235153865-297f9823-d81f-4dac-b7e4-b30fa2522c22.png)

Didn't find the required field on first try but will investigate little deeper.

**Comment by SebastianStehle** [comment]
It has been fixed.

2 issues:

1. Some properties of the integration has been marked as required (SilentIOS...)
2. The validation exception was not producing nice results. Therefore the property name is was not shown.
