### ISSUE TITLE
Dockerfile Error

### ISSUE THREAD

**Issue by jazzdivined** [notifo-io/notifo#197]
![image](https://github.com/notifo-io/notifo/assets/56246068/21c2d5b0-99d8-4cac-bff2-47afecaa696e)
So I tried to build a docker image from the dockerfile. I got this error instead:

error from sender: readdir: open backend\src\*: The filename, directory name, or volume label syntax is incorrect.

**Comment by SebastianStehle** [comment]
Is it on windows or Linux? Because the docker file is built with each commit

**Comment by SebastianStehle** [comment]
Can you try double star here: https://github.com/notifo-io/notifo/blob/main/Dockerfile#L14

```
COPY backend/src/**/*.csproj
```

I can test it out later myself.

**Comment by SebastianStehle** [comment]
I have tested it with WSL2 + Ubuntu and it works fine for me.
