### ISSUE TITLE
Broken user record when notification is created without an existing user

### ISSUE THREAD

**Issue by benjyiw** [notifo-io/notifo#200]
Hello!

I'm using Notifo 1.3.0, and have ran into a bug it seems.

If a notification is created for a user ID that doesn't exist yet, then subsequent attempts to create that user with the same ID will result in two broken user records. In my environment, we upsert users to Notifo with IDs that match our internal system, for ease of correlating users between the two systems. When the problem described happens, those user records are broken until we go into the Mongodb and manually remove everything related to that ID, including notifications.

Obviously, our system could handle the creation of users better to prevent this odd case from happening, but alas, it has happened and I imagine it could happen to others.

Here's a screenshot from MongoDB compass from the Users collection that shows what happens on the backend:
![image](https://github.com/notifo-io/notifo/assets/6757931/6615f51f-6f2f-4483-9a83-bf4d2ce01f1f)
One user is created with the real user ID, and subsequent upserts do not replace it.

The upsert request for the user after the fact is very simple, just an email and ID:
```
POST http://notifo:5000/api/apps/fe05d9b4-9c98-4edd-b7cc-9de42d8f43a1/users
{
  "requests": [
    {
      "emailAddress": "ben<omitted>",
      "fullName": null,
      "id": "6a978c47-6c5b-482d-a29c-1643e8e95c45",
      "phoneNumber": null,
      "preferredLanguage": null,
      "preferredTimezone": null,
      "properties": null,
      "requiresWhitelistedTopics": null,
      "settings": null
    }
  ]
}
```

I'm guessing that the object with the actual user ID is created automatically so that the system can track those counters. But then subsequent upserts on that same ID do not replace it, which causes my problem.

Hope that's enough info.

Thanks!

**Comment by SebastianStehle** [comment]
Yes, thats definitely a bug. I will have a look.
