### ISSUE TITLE
Translate to Turkish

### ISSUE THREAD

**Issue by alibildir** [notifo-io/notifo#219]
Hi,
İ have translated to Turkish. But it is so static. I will change it to dynamic or on startup config (appsettings.json). Please let me if you prefer how would change language?
Good job. After now i want to be a contrubuter for this project.

**Comment by SebastianStehle** [comment]
Aewsome. I have solved it in another project of mine:

This is the general flow:

1. ASP.NET Core already supports the culture selection using a middleware: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?view=aspnetcore-8.0. One of the strategies is to use a cookie. This is already configured: https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo/Startup.cs#L187

2. Somewhere in the user interface we could configure the culture using a list of available languages: https://github.com/Squidex/squidex/blob/master/frontend/src/app/shell/pages/internal/profile-menu.component.ts#L91

3. This lanuage is injected to the frontend using a simple variable, we already do that for options: https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo/Areas/Frontend/Startup.cs#L32

**Comment by alibildir** [comment]
Ok, you have done already. it does not neccesary online changing browser settings is enought i think. i will send pull request #220

**Comment by SebastianStehle** [comment]
I think for now it is okay. But I often override my language ;)
