### ISSUE TITLE
Template API Documentation + SMS Processing

### ISSUE THREAD

**Issue by medcelerate** [notifo-io/notifo#230]
It would be great t have documentation on what values are exposed to liquid in what contexts. I have also noticed that with 1.3.0 it doesn't seem to evaluate the notification.body for sms templates, only the subject. For loops also render as text and are not computed.

**Comment by SebastianStehle** [comment]
Yes, makes sense. In another project I just created an endpoint for that, which can then be used in an integrated help and for auto completion.

**Comment by medcelerate** [comment]
Is there somewhere in the code I can look for for the current injectable
parameters? Also the sms templates seem to fully ignore the message body
param.

**Comment by SebastianStehle** [comment]
In the latest version it is much more unified: https://github.com/notifo-io/notifo/blob/main/backend/src/Notifo.Domain/Liquid/LiquidContext.cs

But in 1.3.0 it is only this one: https://github.com/notifo-io/notifo/blob/1.3.0/backend/src/Notifo.Domain/Channels/Sms/SmsFormatter.cs#L53, which also has not changed that much: https://github.com/notifo-io/notifo/blob/1.2.0/backend/src/Notifo.Domain/Channels/Sms/SmsFormatter.cs

**Comment by medcelerate** [comment]
I’ll update to latest and see if that resolves the sms body being blank

**Comment by SebastianStehle** [comment]
You have to use the current dev version.

**Comment by medcelerate** [comment]
Got it, I’ll migrate over

**Comment by medcelerate** [comment]
Seems like there is a validation error with the current dev version on the sms page, saying text field is required but the API request is sending the text field.

**Comment by SebastianStehle** [comment]
I have fixed that.

**Comment by medcelerate** [comment]
Is it in a new build that has this fix? I'm using the latest from notifo-dev.

**Comment by SebastianStehle** [comment]
mmkK

10p

**Comment by medcelerate** [comment]
Yes, fixed, thanks!

**Comment by SebastianStehle** [comment]
I pushed an improvement where I added a list of properties to sms template page with some other fixes.
