### ISSUE TITLE
Push details popover overlaps Publish dialog.

### ISSUE THREAD

**Issue by sanyandreichuk** [notifo-io/notifo#49]
1. Go to the User Details page
2. Click on the mobile push icon.
3. Click on Publish button.

Actual result:  push details popover visible and overlaps publish dialog.
Expected result: push details popover hidden or publish dialog is above push details popover.

![chrome_2021-06-25_16-15-15](https://user-images.githubusercontent.com/8818052/123430448-dd70c080-d5d0-11eb-9c7f-df5530c018d9.png)

**Comment by SebastianStehle** [comment]
Thank you very much. I have fixed it.
