### ISSUE TITLE
Templatename is not set in editing Mode

### ISSUE THREAD

**Issue by jannishuebl** [notifo-io/notifo#59]
Hi, 

when trying to edit an Email Template the name is not set in the name Textfield. Which causes the name to be empty after saving the Template: 

![image](https://user-images.githubusercontent.com/1532995/144409388-5d72fa4b-6ddc-42c2-bd91-3aeead884036.png)

![image](https://user-images.githubusercontent.com/1532995/144409450-8f63618b-b5a1-426e-b29a-c93d81f32cc3.png)

My current version: docker image: dev-362

**Comment by SebastianStehle** [comment]
Thx, I will have look today.

**Comment by jannishuebl** [comment]
Works :) Thank you :+1:
