### ISSUE TITLE
When trying to edit a Subscription the form is Empty

### ISSUE THREAD

**Issue by jannishuebl** [notifo-io/notifo#60]
![image](https://user-images.githubusercontent.com/1532995/144412742-3f6ec775-6252-4060-a1fa-0a8e6df6b9f3.png)

When trying to edit, the form is empty:

![image](https://user-images.githubusercontent.com/1532995/144412794-b8c8fc46-43ef-4a15-b1ac-83a8cf805a2e.png)

dockerimage: squidex/notifo:dev-362

**Comment by jannishuebl** [comment]
It seems like the Subscription is not saved correctly in first place, when publishing an event the Notification does not have the Email settings, which i provided.: 

![image](https://user-images.githubusercontent.com/1532995/144413745-d610fc10-76fe-4c0f-b86d-ffcd4a01d191.png)

I did not edit the Subscription.

**Comment by SebastianStehle** [comment]
Thx, I will have look today.

**Comment by jannishuebl** [comment]
Works :) Thank you :+1:
