### ISSUE TITLE
Allow subscribing for subtopics for users

### ISSUE THREAD

**Issue by jannishuebl** [notifo-io/notifo#65]
Hi, 

I am implementing notifo notifications in my application right now. But what I would need is: 

1. User can subscribe to "subtopics" eg: 
/users/:id/topic1
/users/:id/topic2
/users/:id/topic3

2. Only the user with :id is allowed to do this, since otherwise other users could subscribe to notifications for another user

Current state: 

In the version docker: notifo:dev-364 it is allowed to subscribe to the subtopics also for other users, but you don't recive notifications for this subtopics at all. 

Is there the plan to support such a feature? I could try to help, but i have no experience in C#, but i could help with the documentation instead.

**Comment by SebastianStehle** [comment]
Hi,

this is already implemented. You can add an allowed topic for an user, then a user can only subscribe to this topic: https://app.notifo.io/api/docs/index.html?url=/api/openapi.json#operation/Users_PostAllowedTopic

It is a prefix, so you would set the prefix /users/:id/ for a user.

**Comment by jannishuebl** [comment]
Hi, 

ah thanks i did not see that. :) 

But when i understand that api right it would be great to have the possiblity to query the allowed topics, eg return it here: 

https://notifo.easierlife.com/api/docs/index.html?url=/api/openapi.json#operation/User_GetUser

and is there a reason not having a GET /api/me/subscriptions endpoint?

**Comment by SebastianStehle** [comment]
Both are valid points. Can you add feature requests (seperate issues) for them?

**Comment by jannishuebl** [comment]
@SebastianStehle 

I tried the allowed topic api, but no notification was send to the user which is subscripte to /users/:id/subtopic. 

I had a look at the code and thought that is code lines prevents the events from being published: 

https://github.com/notifo-io/notifo/blob/041bf57250e6c41af106ef7fed2291ced06bb1c5/backend/src/Notifo.Domain/UserEvents/Pipeline/UserEventPublisher.cs#L209

As far as i understand when the topic starts with users/ it simple creates a dummy subscription for /users/:id and not return the subtopics. 

I tried a fix which you can find in #66, but it does not seem to prevent notifo from sending to topics that are not allowed via the AllowedTopic-api

**Comment by SebastianStehle** [comment]
Yes, exactly. Your code change makes absolutely sense for me :)

**Comment by SebastianStehle** [comment]
Can we close this?

**Comment by jannishuebl** [comment]
sure, thank you!
