### ISSUE TITLE
Firebase Token Error response handling

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#74]
I'm wondering about the error code handling of firebase.
See https://github.com/notifo-io/notifo/blob/ef9b635dbce1905835f2e3db705d8892861136c9/backend/src/Notifo.Domain.Integrations/Firebase/FirebaseMobilePushSender.cs#L62
There is a handling for error code "NotFound" and "InvalidArgument", but on firebase admin doc I can't find the notFound code. Instead for invalidating the token we should wait for "Unregistered". I would expect that this is the also the only response that should trigger an invalidation. All other errors are not related to the life of the token.
<img width="875" alt="Bildschirmfoto 2021-12-14 um 14 21 48" src="https://user-images.githubusercontent.com/10132368/146006812-6271401b-17ee-446f-af15-a00a95d07aa3.png">
https://firebase.google.com/docs/reference/admin/dotnet/namespace/firebase-admin/messaging#namespace_firebase_admin_1_1_messaging_1ac3482b9d4581255dee08b81ac3f677c9

**Comment by SebastianStehle** [comment]
There is no such a code: https://github.com/firebase/firebase-admin-dotnet/blob/f6babbd4e59655f01be4a43230b5be198fc4f8cd/FirebaseAdmin/FirebaseAdmin/ErrorCode.cs

**Comment by CR4567** [comment]
This are the parent errorCodes, but there are specific for messaging.
https://github.com/firebase/firebase-admin-dotnet/blob/master/FirebaseAdmin/FirebaseAdmin/Messaging/MessagingErrorCode.cs
Shouldn't you get these codes?

**Comment by SebastianStehle** [comment]
Sorry, there was another property. I have pushed a potential fix.

**Comment by CR4567** [comment]
ok looks good. That's what I would have expected.
